---
kind: pipeline
type: docker
name: default

steps:
  - name: setup
    image: node:16-slim
    when:
      event:
        - push
    commands:
      - yarn --frozen-lockfile

  - name: prettier
    image: node:16-slim
    when:
      event:
        - push
    depends_on:
      - setup
    commands:
      - yarn prettier:check

  - name: eslint
    image: node:16-slim
    when:
      event:
        - push
    depends_on:
      - setup
    commands:
      - yarn eslint

  - name: build
    image: node:16-slim
    when:
      event:
        - push
    depends_on:
      - setup
    commands:
      - yarn build

  - name: export
    image: node:16-slim
    when:
      event:
        - push
    depends_on:
      - setup
      - build
    commands:
      - yarn export

  - name: cypress
    image: cypress/included:10.3.0
    when:
      event:
        - push
    depends_on:
      - export
    environment:
      CYPRESS_RECORD_KEY:
        from_secret: cypress_record_key
    commands:
      - apt-get -y install procps
      - yarn cypress:ci

  - name: docker
    image: plugins/docker
    when:
      branch:
        - master
      event:
        - push
      status:
        - success
    depends_on:
      - setup
      - prettier
      - eslint
      - build
      - export
    settings:
      registry: https://registry.webkom.dev
      repo: registry.webkom.dev/webkom/kvittering
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - latest
      build_args:
        - RELEASE=${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:7}

  - name: Deploy
    image: abakus/ansible-deploy
    when:
      branch:
        - master
      event: push
      status: success
    settings:
      playbook: /infrastructure/esas/playbooks/deploy.yml
      repository:
        from_secret: infra_repository
      tags:
        - kvittering
      limit: esas
      inventory: /infrastructure/inventory
      vault_password:
        from_secret: ansible_vault_password
      private_key:
        from_secret: infra_deploy_key
    depends_on:
      - docker
