FROM node:10 as builder

WORKDIR /app

RUN apt-get update && apt-get install -y curl
RUN curl -sL https://github.com/openfaas/faas/releases/download/0.9.0/fwatchdog > /usr/bin/fwatchdog \
    && chmod +x /usr/bin/fwatchdog

COPY package.json .
RUN yarn
COPY . /app
RUN yarn build

FROM alpine

COPY --from=builder /app/build/index.html .
COPY --from=builder /usr/bin/fwatchdog .

ENV fprocess="cat index.html"
CMD ["./fwatchdog"]
